config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "trainings#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "about", to: "pages#about"
  get "map", to: "pages#map"
  get "overview", to: "pages#overview"


  resources :favorites
  resources :users, only: [:show, :edit, :update]


  resources :trainings, only: [:show, :index, :new, :create, :destroy, :edit, :update] do
    resources :blocs, only: [:show, :index, :new, :create] do
      resources :lines, only: [:show, :index, :new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bloc.rb
class Bloc < ApplicationRecord
  belongs_to :training
  has_many :lines, dependent: :destroy, inverse_of: :bloc
  accepts_nested_attributes_for :lines, allow_destroy: true, reject_if: :all_blank
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :training
  validates :user, uniqueness: { scope: :training}
end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :bloc
end

app/models/pool.rb
class Pool < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/training.rb
class Training < ApplicationRecord
  has_many :blocs, dependent: :destroy
  accepts_nested_attributes_for :blocs, reject_if: :all_blank, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites
  has_many :trainings, through: :favorites

  has_one_attached :photo

  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/blocs_controller.rb
class BlocsController < ApplicationController
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController


  def index
    @user = current_user
    @favorites = @user.favorites
  end

  def new
    @favorite = Favorite.new
  end

  def create
    @favorite = Favorite.new(favorite_params)

    if @favorite.save
      render json: { status: "created", favorite: @favorite }
    else
      render json: { status: "error", errors: @favorite.errors.full_messages }, status: :unprocessable_entity
    end
  end


  def destroy
    @favorite = Favorite.find(params[:id])
    if @favorite.destroy
      render json: { status: 'removed' }
    else
      render json: { status: 'error', message: 'Failed to remove favorite' }, status: :unprocessable_entity
    end
  end




  private
  def favorite_params
    params.require(:favorite).permit(:user_id, :training_id)
  end

end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @trainings = Training.all
  end

  def about
  end

  def overview
  end

  def map
    @pools = Pool.all
    @markers = @pools.geocoded.map do |pool|
      {
        lat: pool.latitude,
        lng: pool.longitude
      }
    end
  end

end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: %i[show edit update destroy]

  def index
    @trainings = Training.all
    @favorites = current_user.trainings
  end

  def show
    @bloc = Bloc.new
    @bloc.training = @training
  end

  def new
    @training = Training.new
    #@training.blocs.build
    # @training.blocs.build.lines.build
  end

  def create
    @training = Training.new(training_params)
    if @training.save
      redirect_to root_path
    end
  end

  def edit
    @training = Training.find(params[:id])
    #@training.blocs.build.lines.build

  end

  def update
    @training.update(training_params)
    redirect_to root_path
  end

  def destroy
    @training.destroy
    redirect_to root_path
  end

  private

  def set_training
    @training = Training.find(params[:id])
  end

  def training_params
    params.require(:training).permit(:title, :date, :content, blocs_attributes: [:id, :_destroy, :quantity, lines_attributes: [:id, :_destroy, :quantity, :meters, :exercise, :distance, :start_time]])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Profile picture updated successfully.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:photo, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/favorites/index.html.erb
 <div class="cards">
  <% @favorites.each do |favorite| %>
    <% training = favorite.training %>
    <div class= "card">
      <div class="card-title">
        <h4><%= training.title %></h4>
        <h6><%= training.date %></h6>
      </div>

      <% training.blocs.each do |bloc| %>
        <div class="bloc">
          <div class="bloc-quantity">
            <%= bloc.quantity %>x
          </div>

          <div class="lines">
            <% bloc.lines.each do |line| %>
              <div class="line">
              <div class = "line-left">
                <%= line.quantity %>x
                <%= line.distance %>
                <%= line.exercise %>
                </div>
                <div class = "line-right">
                <% if line.start_time? %>
                Start:
                <%= line.start_time %>
                <% end %>
                </div>
                </div>
            <% end %>
          </div>

        </div>
      <% end %>

      <div class="star btn" data-controller="favorite" data-training-id="<%= training.id %>" data-action="click->favorite#toggle" >
          <i class="fa-solid fa-star fa-2xl yellow-star" data-favorite-target="star" data-training-id="<%= training.id %>" ></i>
      </div>


    </div>
  <% end %>


</div>

app/views/favorites/new.html.erb
<%= simple_form_for (@favorite) do |f| %>
<%= f.input :user_id %>
<%= f.input :training_id %>
<%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Swim Plan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
     <meta name="description" content="Get your daily swim training">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>

    <body><%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
Test scrolable items
<div class="wrapper">
  <i class="fa-solid fa-angle-left"></i>
  <div class="cards2">
    <% @trainings = Training.all %>
    <% @trainings.each do |t | %>
      <div class="test2">
      <%= t.title %>
      </div>
    <% end %>

  </div>
    <i class="fa-solid fa-angle-right"></i>
</div>

app/views/pages/home.html.erb
<div class="container-h">
  <h1>SwimPlanAA</h1>
  <p>Get your daily swim training</p>

  <div class="cards">
  <% @trainings.each do |training| %>
    <div class= "card">
      <%= link_to training_path(training) do  %>
        <div class="card-title">
          <h3><%= training.title %></h3>
        </div>
      <% end %>
      <% training.blocs.each do |bloc| %>
        <div class="bloc">
          <div class="bloc-quantity">
            <%= bloc.quantity %>
          </div>

          <div class="lines">
            <% bloc.lines.each do |line| %>
              <div class= "line">
                <div>
                  <%= line.quantity %> <br>
                  <%= line.distance %>
                  <%= line.exercise %>

                </div>
                <div>
                <%= line.start_time %>
                </div>
                </div>
               <br>
            <% end %>
          </div>

        </div>
      <% end %>
       <%= link_to "Edit Training", edit_training_path(training), class:"button-edit" %>
       <%= link_to "Delete", training_path(training), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"button-delete" %>
    </div>
  </div>
  <% end %>
  <br>
    <%= link_to "New training", new_training_path %>
    <br>
    <%= link_to "about us", about_path %>

    <%= link_to 'Overview', overview_path %>


</div>

app/views/pages/map.html.erb
<h4>Map</h4>
<p>Find pools close to you ! And find other SwimPlan users</p>
<p>Select a city: </p>
<div class="map-container"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

app/views/pages/overview.html.erb
<!-- app/views/your_controller/overview.html.erb -->
<!-- Example dropdown filters -->
<div class="filters">
  <div class="filter">
    <label for="thematic-filter">Thematic:</label>
    <select id="thematic-filter">
      <option value="all">All</option>
      <option value="option1">Option 1</option>
      <option value="option2">Option 2</option>
      <!-- Add more thematic options as needed -->
    </select>
  </div>

  <div class="filter">
    <label for="stroke-filter">Swim Stroke:</label>
    <select id="stroke-filter">
      <option value="all">All</option>
      <option value="stroke1">Stroke 1</option>
      <option value="stroke2">Stroke 2</option>
      <!-- Add more swim stroke options as needed -->
    </select>
  </div>



<div class="overview_card_grid">
  <% 12.times do %>
    <div class="overview_card">
      <!-- Content for each card goes here -->
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fa-solid fa-person-swimming fa-1x"></i>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "#", class: "nav-link" do%>
            <% if current_user.photo.attached?  %>
            ok
            <% else %>
            <i class="fa-solid fa-user"></i>

            <% end %>
            <% end %>

          <li class="nav-item">
            <%= link_to "#", class: "nav-link" do%>
            <i class="fa-solid fa-envelope fa-xl"></i>
            <% end %>
          </li>
          <li class="nav-item dropdown">

               <%= image_tag "tschab.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>



            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Favorites", favorites_path, class: "dropdown-item" %>

              <%= link_to "Settings", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/trainings/_bloc_fields.html.erb
<div class="nested-fields">
  <div class="bloc-field">
  <%= f.input :quantity %>
  </div>


  <div class="line-fields">
  <h3>Lines</h3>
  <div id="blocs">
    <%= f.simple_fields_for :lines do |line| %>
      <%= render "line_fields", f: line %>
    <% end %>
    <div class="links">
      <%= link_to_add_association "Add Line", f, :lines %>
    </div>
  </div>
  </div>
 <%= link_to_remove_association "Remove Bloc", f %>
</div>

app/views/trainings/_form.html.erb
<%= simple_form_for(@training) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :date %>
    <h3>Blocs</h3>

    <div id="blocs">
    <%= f.simple_fields_for :blocs do |bloc| %>
    <div class="bloc-form">
    <%= render "bloc_fields", f: bloc %>
    </div>
    <% end %>
    <div class="links">
    <%= link_to_add_association "Add Bloc", f, :blocs %>
    </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/trainings/_line_fields.html.erb
<div class="nested-fields">
  <%= f.input :quantity%>
  <%= f.input :distance %>
  <%= f.input :exercise %>
  <%= f.input :start_time %>

  <%= link_to_remove_association "Remove Line", f %>
</div>

app/views/trainings/edit.html.erb
<h1>Editing project</h1>

<%= simple_form_for(@training, :method => 'patch') do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <%= f.input :title %>
  <%= f.input :date %>
  <h3>Blocs</h3>

  <div id="blocs">
    <%= f.simple_fields_for :blocs do |bloc| %>
      <% # Use `bloc.object.id` to get the ID of the existing bloc %>
      <div class="bloc-form" id="bloc_<%= bloc.object.id %>">
        <div class="bloc-field">
          <%= bloc.input :quantity %>
        </div>
        <div class="line-fields">
          <h3>Lines</h3>
          <%= bloc.simple_fields_for :lines do |line| %>
            <% # Use `line.object.id` to get the ID of the existing line %>
            <div class="nested-fields" id="line_<%= line.object.id %>">
              <%= line.input :quantity%>
              <%= line.input :distance %>
              <%= line.input :exercise %>
              <%= line.input :start_time %>
              <%= link_to_remove_association "Remove Line", line %>
            </div>
          <% end %>
        </div>
        <div class="links">
          <%= link_to_add_association "Add Line", bloc, :lines  %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="links">
    <%= link_to_add_association "Add Bloc", f, :blocs  %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to "Back to trainings", trainings_path %>

app/views/trainings/index.html.erb
<body class="index-page">
  <div class="container">
    <div class="container-title">
      <h1>SwimPlan</h1>
      <p>Get your daily swim training</p>
    </div>

    <div class="cards" data-controller="scroll" data-scroll-target="cards">
      <div>
        <i class="fa-solid fa-angle-left arrow-icon left-arrow" data-action="click->scroll#scrollLeft"></i>
      </div>
      <% @trainings.each_with_index do |training, index| %>
        <% if index == 0 %>
          <div class="card first-card" data-controller="workout">
        <% elsif index == @trainings.count - 1 %>
          <div class="card last-card" data-controller="workout">
        <% else %>
          <div class="card" data-controller="workout">
       <% end %>
          <%= link_to training_path(training) do %>
            <div class="card-title">
              <h4><%= training.title %></h4>
              <h6><%= training.date %></h6>
            </div>
          <% end %>

          <% training.blocs.each do |bloc| %>
            <div class="bloc">
              <div class="bloc-quantity">
                <%= bloc.quantity %>x
              </div>

              <div class="lines">
                <% bloc.lines.each do |line| %>
                  <div class="line">
                    <div class="line-left">
                      <%= line.quantity %>x
                      <%= line.distance %>
                      <%= line.exercise %>
                    </div>
                    <div class="line-right">
                      <% if line.start_time? %>
                        Start:
                        <%= line.start_time %>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>

          <div class="edit-link">
            <%= link_to edit_training_path(training) do %>
              <i class="fa-regular fa-pen-to-square"></i>
            <% end %>

            <br>

            <%= link_to training_path(training), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
              <i class="fa-solid fa-trash"></i>
            <% end %>
          </div>

          <div class="star btn" data-controller="favorite" data-training-id="<%= training.id %>" data-action="click->favorite#toggle" data-favorite-path="<%= favorites_path %>">
            <% if @favorites.include? training %>
              <% favorite = Favorite.find_by(training_id: training.id, user_id: current_user.id) %>
              <i class="fa-solid fa-star fa-2xl yellow-star" data-favorite-target="star" data-training-id="<%= training.id %>" data-current-user-id="<%= current_user.id %>" data-favorite-id="<%= favorite.id %>"></i>
            <% else %>
              <i class="fa-regular fa-star fa-2xl" data-favorite-target="star" data-training-id="<%= training.id %>" data-current-user-id="<%= current_user.id %>"></i>
            <% end %>
          </div>
        </div>
      <% end %>
      <div>
        <i class="fa-solid fa-angle-right arrow-icon right-arrow" data-action="click->scroll#scrollRight"></i>
      </div>
    </div>

    <div class="container-footer">
      <br>
      <%= link_to "New training", new_training_path %>
      <br>

    </div>
  </div>

  <div class="footer">
    <div class="link-home">
    <%= link_to "Home", "#" %>
    </div>
    <div class="about">
    <%= link_to "About us", about_path %>
    </div>
    <div class="find-pools">
    <%= link_to map_path do  %>
     <i class="fa-solid fa-location-arrow fa-xl"></i> Find pools
     <% end %>
     </div>

     <div class="link-settings">
    <%= link_to "Settings", "#" %>
    </div>
  </div>
</body>

app/views/trainings/new.html.erb
<div class="form-training">
<h1>New training</h1>

<%= render "form", training: @training %>


  <%= link_to "Back to trainings", trainings_path %>

</div>

app/views/trainings/show.html.erb
<h2><%= @training.title %></h2>

<% @training.blocs.each do |bloc| %>
  <%= bloc.quantity %>
  <% bloc.lines.each do |line| %>
    <%= line.quantity %>
    <%= line.distance %>
    <%= line.exercise %>
    <%= line.start_time %>

  <% end %>
<% end %>


<h4>Add blocs</h4>
<%= simple_form_for [@training, @bloc] do |f| %>
  <%= f.input :quantity %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<%# <%= turbo_frame_tag "name" do %>
<body class="profile-container">
<div class="user-container">
<div class="user-info">
<h4>Username</h4>
<%= @user.username %>
<br>
<br>

<%= simple_form_for @user, url: user_path(@user), method: :patch, html: { class: 'user-form' } do |form| %>
  <div class="right-save">
  <%= form.input :username, label:" Modify Username" %>
  <%= form.button :submit, 'Update', class: 'custom-save-button'%>
  </div>
<% end %>


<h4>Picture</h4>

<% if @user.photo.attached? %>
  <%= image_tag @user.photo %>
<% else %>
  <i class="fa-solid fa-user fa-2xl"></i>
<% end %>
<br>
<br>
<h6></h6>
<%= simple_form_for @user, url: user_path(@user), method: :patch, html: { multipart: true, class: 'user-form' } do |form| %>
  <div class="right-save">
  <%= form.input :photo, as: :file, label: "Modify Picture" %>
  <%= form.button :submit, 'Update' ,class: 'custom-save-button'%>
  </div>
<% end %>
</div>

<div class="training-info">
<h4>Number of Trainings:</h4>

<h4>Number of Favorite Trainings: </h4>

<br>

<p>MAP</p>

</div>

</div>
</body>